/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EffectType = IDL.Variant({
  'static' : IDL.Null,
  'rainbow' : IDL.Null,
  'music' : IDL.Null,
  'fire' : IDL.Null,
  'breathe' : IDL.Null,
});
export const ScheduledTask = IDL.Record({
  'startTime' : IDL.Text,
  'daysActive' : IDL.Vec(IDL.Bool),
  'endTime' : IDL.Text,
  'effect' : EffectType,
  'taskId' : IDL.Nat,
});
export const AmbiSettings = IDL.Record({
  'fps' : IDL.Nat,
  'currentPowerState' : IDL.Bool,
  'autoOnTime' : IDL.Text,
  'staticColor' : IDL.Text,
  'ledCount' : IDL.Nat,
  'scheduleDays' : IDL.Vec(IDL.Bool),
  'autoOffTime' : IDL.Text,
  'autoPowerEnabled' : IDL.Bool,
  'selectedEffect' : EffectType,
  'screenCaptureActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addTask' : IDL.Func(
      [EffectType, IDL.Text, IDL.Text, IDL.Vec(IDL.Bool)],
      [IDL.Nat],
      [],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(ScheduledTask)], ['query']),
  'getSettings' : IDL.Func([], [AmbiSettings], ['query']),
  'getTasksForDay' : IDL.Func([IDL.Nat], [IDL.Vec(ScheduledTask)], ['query']),
  'removeTask' : IDL.Func([IDL.Nat], [], []),
  'updateSettings' : IDL.Func([AmbiSettings], [], []),
  'updateTaskPowerState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EffectType = IDL.Variant({
    'static' : IDL.Null,
    'rainbow' : IDL.Null,
    'music' : IDL.Null,
    'fire' : IDL.Null,
    'breathe' : IDL.Null,
  });
  const ScheduledTask = IDL.Record({
    'startTime' : IDL.Text,
    'daysActive' : IDL.Vec(IDL.Bool),
    'endTime' : IDL.Text,
    'effect' : EffectType,
    'taskId' : IDL.Nat,
  });
  const AmbiSettings = IDL.Record({
    'fps' : IDL.Nat,
    'currentPowerState' : IDL.Bool,
    'autoOnTime' : IDL.Text,
    'staticColor' : IDL.Text,
    'ledCount' : IDL.Nat,
    'scheduleDays' : IDL.Vec(IDL.Bool),
    'autoOffTime' : IDL.Text,
    'autoPowerEnabled' : IDL.Bool,
    'selectedEffect' : EffectType,
    'screenCaptureActive' : IDL.Bool,
  });
  
  return IDL.Service({
    'addTask' : IDL.Func(
        [EffectType, IDL.Text, IDL.Text, IDL.Vec(IDL.Bool)],
        [IDL.Nat],
        [],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(ScheduledTask)], ['query']),
    'getSettings' : IDL.Func([], [AmbiSettings], ['query']),
    'getTasksForDay' : IDL.Func([IDL.Nat], [IDL.Vec(ScheduledTask)], ['query']),
    'removeTask' : IDL.Func([IDL.Nat], [], []),
    'updateSettings' : IDL.Func([AmbiSettings], [], []),
    'updateTaskPowerState' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };