/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AmbiSettings {
  'fps' : bigint,
  'currentPowerState' : boolean,
  'autoOnTime' : string,
  'staticColor' : string,
  'ledCount' : bigint,
  'scheduleDays' : Array<boolean>,
  'autoOffTime' : string,
  'autoPowerEnabled' : boolean,
  'selectedEffect' : EffectType,
  'screenCaptureActive' : boolean,
}
export type EffectType = { 'static' : null } |
  { 'rainbow' : null } |
  { 'music' : null } |
  { 'fire' : null } |
  { 'breathe' : null };
export interface ScheduledTask {
  'startTime' : string,
  'daysActive' : Array<boolean>,
  'endTime' : string,
  'effect' : EffectType,
  'taskId' : bigint,
}
export interface _SERVICE {
  'addTask' : ActorMethod<[EffectType, string, string, Array<boolean>], bigint>,
  'getAllTasks' : ActorMethod<[], Array<ScheduledTask>>,
  'getSettings' : ActorMethod<[], AmbiSettings>,
  'getTasksForDay' : ActorMethod<[bigint], Array<ScheduledTask>>,
  'removeTask' : ActorMethod<[bigint], undefined>,
  'updateSettings' : ActorMethod<[AmbiSettings], undefined>,
  'updateTaskPowerState' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];