/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScheduledTask {
    startTime: string;
    daysActive: Array<boolean>;
    endTime: string;
    effect: EffectType;
    taskId: bigint;
}
export interface AmbiSettings {
    fps: bigint;
    currentPowerState: boolean;
    autoOnTime: string;
    staticColor: string;
    ledCount: bigint;
    scheduleDays: Array<boolean>;
    autoOffTime: string;
    autoPowerEnabled: boolean;
    selectedEffect: EffectType;
    screenCaptureActive: boolean;
}
export enum EffectType {
    static_ = "static",
    rainbow = "rainbow",
    music = "music",
    fire = "fire",
    breathe = "breathe"
}
export interface backendInterface {
    addTask(effect: EffectType, startTime: string, endTime: string, daysActive: Array<boolean>): Promise<bigint>;
    getAllTasks(): Promise<Array<ScheduledTask>>;
    getSettings(): Promise<AmbiSettings>;
    getTasksForDay(dayIdx: bigint): Promise<Array<ScheduledTask>>;
    removeTask(taskId: bigint): Promise<void>;
    updateSettings(newSettings: AmbiSettings): Promise<void>;
    updateTaskPowerState(taskId: bigint, newState: boolean): Promise<void>;
}
import type { AmbiSettings as _AmbiSettings, EffectType as _EffectType, ScheduledTask as _ScheduledTask } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTask(arg0: EffectType, arg1: string, arg2: string, arg3: Array<boolean>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(to_candid_EffectType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(to_candid_EffectType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async getAllTasks(): Promise<Array<ScheduledTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<AmbiSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return from_candid_AmbiSettings_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return from_candid_AmbiSettings_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForDay(arg0: bigint): Promise<Array<ScheduledTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForDay(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForDay(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTask(arg0);
            return result;
        }
    }
    async updateSettings(arg0: AmbiSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(to_candid_AmbiSettings_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(to_candid_AmbiSettings_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTaskPowerState(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskPowerState(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskPowerState(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AmbiSettings_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AmbiSettings): AmbiSettings {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_EffectType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EffectType): EffectType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ScheduledTask_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScheduledTask): ScheduledTask {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: string;
    daysActive: Array<boolean>;
    endTime: string;
    effect: _EffectType;
    taskId: bigint;
}): {
    startTime: string;
    daysActive: Array<boolean>;
    endTime: string;
    effect: EffectType;
    taskId: bigint;
} {
    return {
        startTime: value.startTime,
        daysActive: value.daysActive,
        endTime: value.endTime,
        effect: from_candid_EffectType_n6(_uploadFile, _downloadFile, value.effect),
        taskId: value.taskId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fps: bigint;
    currentPowerState: boolean;
    autoOnTime: string;
    staticColor: string;
    ledCount: bigint;
    scheduleDays: Array<boolean>;
    autoOffTime: string;
    autoPowerEnabled: boolean;
    selectedEffect: _EffectType;
    screenCaptureActive: boolean;
}): {
    fps: bigint;
    currentPowerState: boolean;
    autoOnTime: string;
    staticColor: string;
    ledCount: bigint;
    scheduleDays: Array<boolean>;
    autoOffTime: string;
    autoPowerEnabled: boolean;
    selectedEffect: EffectType;
    screenCaptureActive: boolean;
} {
    return {
        fps: value.fps,
        currentPowerState: value.currentPowerState,
        autoOnTime: value.autoOnTime,
        staticColor: value.staticColor,
        ledCount: value.ledCount,
        scheduleDays: value.scheduleDays,
        autoOffTime: value.autoOffTime,
        autoPowerEnabled: value.autoPowerEnabled,
        selectedEffect: from_candid_EffectType_n6(_uploadFile, _downloadFile, value.selectedEffect),
        screenCaptureActive: value.screenCaptureActive
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    static: null;
} | {
    rainbow: null;
} | {
    music: null;
} | {
    fire: null;
} | {
    breathe: null;
}): EffectType {
    return "static" in value ? EffectType.static : "rainbow" in value ? EffectType.rainbow : "music" in value ? EffectType.music : "fire" in value ? EffectType.fire : "breathe" in value ? EffectType.breathe : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ScheduledTask>): Array<ScheduledTask> {
    return value.map((x)=>from_candid_ScheduledTask_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AmbiSettings_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AmbiSettings): _AmbiSettings {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_EffectType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EffectType): _EffectType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fps: bigint;
    currentPowerState: boolean;
    autoOnTime: string;
    staticColor: string;
    ledCount: bigint;
    scheduleDays: Array<boolean>;
    autoOffTime: string;
    autoPowerEnabled: boolean;
    selectedEffect: EffectType;
    screenCaptureActive: boolean;
}): {
    fps: bigint;
    currentPowerState: boolean;
    autoOnTime: string;
    staticColor: string;
    ledCount: bigint;
    scheduleDays: Array<boolean>;
    autoOffTime: string;
    autoPowerEnabled: boolean;
    selectedEffect: _EffectType;
    screenCaptureActive: boolean;
} {
    return {
        fps: value.fps,
        currentPowerState: value.currentPowerState,
        autoOnTime: value.autoOnTime,
        staticColor: value.staticColor,
        ledCount: value.ledCount,
        scheduleDays: value.scheduleDays,
        autoOffTime: value.autoOffTime,
        autoPowerEnabled: value.autoPowerEnabled,
        selectedEffect: to_candid_EffectType_n1(_uploadFile, _downloadFile, value.selectedEffect),
        screenCaptureActive: value.screenCaptureActive
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EffectType): {
    static: null;
} | {
    rainbow: null;
} | {
    music: null;
} | {
    fire: null;
} | {
    breathe: null;
} {
    return value == EffectType.static ? {
        static_: null
    } : value == EffectType.rainbow ? {
        rainbow: null
    } : value == EffectType.music ? {
        music: null
    } : value == EffectType.fire ? {
        fire: null
    } : value == EffectType.breathe ? {
        breathe: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
